[package]
name = "moon"
version = "0.1.0"
authors = ["ZeroX-DG <viethungax@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "components/html",
  "components/dom",
  "components/css",
  "components/io",
  "components/style",
  "components/layout",
  "components/test_utils",
  "components/painting",
  "components/ipc",
  "components/message",
  "components/tree",
  "rendering"
]

[dependencies]
ipc = { version = "*", path = "./components/ipc" }
message = { version = "*", path = "./components/message" }
pixels = "0.2"
winit = "0.24.0"
simple-logging = "*"
dirs = "2.0.2"
log = "*"
flume = "*"
clap = "*"