[tasks.build]
workspace = false
command = "cargo"
args = ["build"]

[tasks.example]
workspace = false
dependencies = ["build"]
script = '''
cd target/debug && ./moon render --once --html=../../fixtures/test.html --size=500x300 --output=../../image.png

'''

[tasks.try]
workspace = false
dependencies = ["build"]
script = '''
cd target/debug && ./moon render --once --html=../../fixtures/${@}.html --size=500x300 --output=../../image.png

'''

[tasks.output]
workspace = false
dependencies = ["build"]
script = '''
cd target/debug && ./moon render --once --html=../../fixtures/${@}.html --size=500x300 --output=../../image.png
'''
