[tasks.renderer]
workspace = false
script = '''
cd ./rendering && cargo build
'''

[tasks.kernel]
workspace = false
command = "cargo"
args = ["build"]

[tasks.build]
run_task = [
	{ name = "renderer" },
	{ name = "kernel" },
]

[tasks.start]
workspace = false
dependencies = ["renderer"]
command = "cargo"
args = ["run"]

[tasks.example]
workspace = false
dependencies = ["renderer"]
command = "cargo"
args = ["run", "--", "--html", "fixtures/test.html", "--css", "fixtures/test.css"]

[tasks.try]
workspace = false
dependencies = ["renderer"]
command = "cargo"
args = ["run", "--", "--html", "fixtures/${@}.html", "--css", "fixtures/${@}.css"]
