[tasks.build]
workspace = false
command = "cargo"
args = ["build"]

[tasks.example]
workspace = false
dependencies = ["build"]
script = '''
cd target/debug && ./moon --html=../../fixtures/test.html --css=../../fixtures/test.css
'''

[tasks.try]
workspace = false
dependencies = ["build"]
script = '''
cd target/debug && ./moon --html=../../fixtures/${@}.html --css=../../fixtures/${@}.css
'''

[tasks.output]
workspace = false
dependencies = ["build"]
script = '''
cd target/debug && ./moon render-testing --html=../../fixtures/${@}.html --css=../../fixtures/${@}.css --size=500x300 --output=../../image.png
'''
