[tasks.renderer]
workspace = false
script = '''
cd ./rendering && cargo build
'''

[tasks.kernel]
workspace = false
command = "cargo"
args = ["build"]

[tasks.build]
run_task = [
	{ name = "renderer" },
	{ name = "kernel" },
]

[tasks.example]
workspace = false
dependencies = ["renderer", "kernel"]
script = '''
cd target/debug && ./moon --html ../../fixtures/test.html --css ../../fixtures/test.css
'''

[tasks.try]
workspace = false
dependencies = ["renderer", "kernel"]
script = '''
cd target/debug && ./moon --html ../../fixtures/${@}.html --css ../../fixtures/${@}.css
'''

[tasks.output]
workspace = false
script = '''
cd ./rendering && cargo run -- --html ../fixtures/${@}.html --css ../fixtures/${@}.css --output image.png --mode headless
'''