[package]
name = "render"
version = "0.1.0"
authors = ["ZeroX-DG <viethungax@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html = { version="*", path="../components/html" }
dom = { version="*", path="../components/dom" }
css = { version="*", path="../components/css" }
style = { version="*", path="../components/style" }
layout = { version="*", path="../components/layout" }
painting = { version="*", path="../components/painting" }
gfx = { version="*", path="../components/gfx" }
ipc = { version="*", path="../components/ipc" }
message = { version="*", path="../components/message" }
dirs = "2.0.2"
log = "*"
serde = { version = "*", features = ["derive"] }
futures = "*"
